config/routes.rb
SampleApp::Application.routes.draw do
  match '/rate' => 'rater#create', :as => 'rate'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :hotels, only: [:create, :destroy]

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/views/shared/_delete_link.html.erb
<%= link_to "delete", object, method: :delete, data: {confirm: "You sure?"},
                                                                                        title: object.title %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-error">
    The form contains <%= pluralize(object.errors.count, "error") %>
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li>* <%= msg %></li>
    <%end%>
  </ul>
</div>
<%end%>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol class="microposts">
  <%= render partial: 'shared/feed_item', collection: @feed_items %>
</ol>
<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.title%></span>
    <p><span class="title">Room description:</span><%= feed_item.room_description %>
    <p><span class="title">Include breakfast:</span><%= feed_item.include_breakfast %>
    <p><span class="title">Price:</span> <%= feed_item.price %>
    <p><span class="title">Adress:</span> <%= feed_item.adress %></span>
      <p><span class="title">Stars:</span> <%= feed_item.star_rate_hotel %></span>
      <p><%= image_tag feed_item.photo.url%>
  <p><span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at)%> ago.
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago. Stars : <%= rating_for feed_item, "stars", :star => 5 %>
  </span>
  <% if current_user?(feed_item.user) %>
    <%= render partial: 'shared/delete_link', locals: {object: feed_item} %>
      <% end %>
</li>

app/views/shared/_hotel_form.html.erb
<%= form_for(@hotel) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :title, placeholder: "New hotel title..." %>
    <%= f.text_area :room_description, placeholder: "About room..." %>
    <%= f.text_field :price, placeholder: "Price?" %>
    <%= f.text_field :adress, placeholder: "Adress?" %>
    <%= f.check_box :include_breakfast%>
    <%= f.label "Include breakfast?", class: "checkbox inline" %>
<br><% ["1 star", "2 star", "3 star", "4 star", "5 star"].each do |item| %>
  <%= f.radio_button :star_rate_hotel, item %> <%= item %><br />
<% end %>
<p> Upload photo hotel(optionaly)
<%= f.file_field :photo %>
  </div>
  <p>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_non_sign_in_user.html.erb
<div class="center hero-unit">
<h1>Hotel Advisor</h1>
<h2>
Welcome to our website
</h2>
 <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("HAlogo.jpg", alt: "HA"), '#' %>

app/views/shared/_sign_in_user.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <%= render 'shared/user_info' %>
    </section>
    <section>
      <%= render 'shared/hotel_form' %>
    </section>
  </aside>
<div class="span8">
  <h3>Hotels Feed</h3>
  <%= render 'shared/feed' %>
</div>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.hotels.count, "hotel") %>
</span>